version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directories:
    - /.github/workflows
    - /.github/actions/setup-hwloc-dependencies
    - /.github/actions/system-information
  schedule:
    interval: weekly
