[release_like_test]
fail-immediately = true
features = "hwloc-latest"
implicit-test-threads = true
profile = "release_like_test"
skip-clean = true
workspace = true

[normal_test]
fail-immediately = true
features = "hwloc-latest"
implicit-test-threads = true
skip-clean = true
workspace = true
