language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - osx
  - linux
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
branches:
  only:
    - master
before_install:
  - sudo apt-get install hwloc libhwloc-dev
install:
  - wget http://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.1.tar.gz
  - tar -xzvf hwloc-1.11.1.tar.gz
  - cd hwloc-1.11.1  && ./configure && make && sudo make install
