language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
os:
  - osx
  - linux
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
branches:
  only:
    - master
before_install:
  - brew update
  - brew install hwloc
addons:
  apt:
    packages:
      - hwloc
      - libhwloc-dev
