language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
os:
  - osx
  - linux
matrix:
  allow_failures:
    - rust: nightly
install:
  - wget http://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.1.tar.gz
  - tar -xzvf hwloc-1.11.1.tar.gz
  - cd hwloc-1.11.1  && ./configure --prefix=$HOME/hwloc && make && make install