[package]
name = "hwloc"
version = "0.1.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
description = "Rust bindings for the hwloc hardware locality library."

[dependencies]
libc = "0.2.1"
num = "0.1.27"