[package]
name = "hwloc"
version = "0.2.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
license = "MIT"
keywords = ["hwloc"]
description = "Rust bindings for the hwloc hardware locality library."
repository = "https://github.com/daschl/hwloc-rs"
homepage = "https://github.com/daschl/hwloc-rs"
build = "build.rs"
links = "hwloc"
readme = "README.md"

[dependencies]
libc = "0.2.3"
errno = "0.1.5"
num = "0.1.29"
bitflags = "0.3.3"

[build-dependencies]
pkg-config = "0.3.6"
