name: 'Query system information'
description: 'Collect useful system info for hwloc bug reports'
runs:
  using: "composite"
  steps:
    - name: Query system information
      if: runner.os == 'Linux'
      shell: bash
      run: hwloc-gather-topology myhost

    - name: Query system information
      if: runner.os == 'macOS'
      shell: bash
      run: |
          sysctl hw
          sysctl machdep
          hwloc-gather-cpuid
          for f in myhost.*; do
            printf "\n=== Output file '%s' ===" "${f}"
            cat "${f}"
          done

    - name: Query system information
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
          coreinfo64 -accepteula -cgnlsm
          hwloc-gather-cpuid
          echo ""
          echo "=== Output file 'cpuid' ==="
          Dir -Recurse cpuid | type